-- Textile Mill
-- (if you use EEVP mod, this building will be removed because it already has Cloth Mill and both are the same thing)
UPDATE Buildings SET
PrereqTech = 'TECH_STEAM_POWER', Strategy = 'TXT_KEY_BUILDING_TEXTILE_MILL_STRATEGY',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_SEAPORT'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_SEAPORT'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_SEAPORT')
WHERE Type = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_YieldChanges SET
Yield = 2
WHERE BuildingType = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_ResourceYieldChanges SET
YieldType = 'YIELD_GOLD', Yield = 1
WHERE BuildingType = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_LocalResourceOrs
WHERE BuildingType = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldFromYieldPercent (BuildingType, YieldIn, YieldOut, Value)
SELECT 'BUILDING_TEXTILE_MILL', 'YIELD_PRODUCTION', 'YIELD_GOLD', 5
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_ClassesNeededInCity
SELECT 'BUILDING_TEXTILE_MILL', 'BUILDINGCLASS_AQUEDUCT'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_Flavors
WHERE BuildingType = 'BUILDING_TEXTILE_MILL' AND FlavorType = 'FLAVOR_GROWTH'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_Flavors SET
Flavor = 25
WHERE BuildingType = 'BUILDING_TEXTILE_MILL' AND FlavorType = 'FLAVOR_PRODUCTION'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_GOLD] Gold for every 20 [ICON_PRODUCTION] Production generated by the City.[NEWLINE]
[NEWLINE]Nearby [ICON_RES_SHEEP] Sheep: +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_SILK] Silk: +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_COTTON] Cotton: +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_DYE] Dye: +1 [ICON_GOLD] Gold.'
WHERE Tag = 'TXT_KEY_BUILDING_TEXTILE_MILL_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT OR REPLACE INTO Language_en_US (Text, Tag)
SELECT 'The {TXT_KEY_BUILDING_TEXTILE_MILL} is an Industrial-era building which generates [ICON_GOLD] Gold based on a small amount of the City''s current [ICON_PRODUCTION] Production output, also improves [ICON_GOLD] Gold output on all textile-related resources. '||
'The City must already possess an {TXT_KEY_BUILDING_AQUEDUCT} before a {TXT_KEY_BUILDING_TEXTILE_MILL} can be constructed.',
'TXT_KEY_BUILDING_TEXTILE_MILL_STRATEGY'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Delete all Textile Mill references if Cloth Mill exists
DELETE FROM Building_YieldChanges
WHERE BuildingType = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_EE_CLOTH_MILL')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_YieldFromYieldPercent
WHERE BuildingType = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_EE_CLOTH_MILL')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_ResourceYieldChanges
WHERE BuildingType = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_EE_CLOTH_MILL')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_ClassesNeededInCity
WHERE BuildingType = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_EE_CLOTH_MILL')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Buildings
WHERE Type = 'BUILDING_TEXTILE_MILL'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_EE_CLOTH_MILL')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Ranch
UPDATE Buildings SET
PrereqTech = 'TECH_ECONOMICS', Strategy = 'TXT_KEY_BUILDING_RANCH_STRATEGY',
NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_STABLE'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_WINDMILL'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_WINDMILL'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_WINDMILL')
WHERE Type = 'BUILDING_RANCH'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_UnitCombatProductionModifiers
SELECT 'BUILDING_RANCH', Type, 10 FROM UnitCombatInfos
WHERE Type IN ('UNITCOMBAT_SETTLER', 'UNITCOMBAT_WORKER')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldFromInternalTR (BuildingType, YieldType, Yield)
SELECT 'BUILDING_RANCH', Type, 1 FROM Yields
WHERE Type IN ('YIELD_FOOD', 'YIELD_PRODUCTION')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldFromBirth (BuildingType, YieldType, Yield)
SELECT 'BUILDING_RANCH', 'YIELD_PRODUCTION', 10
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_Flavors
SET Flavor = 20
WHERE BuildingType = 'BUILDING_RANCH' AND FlavorType IN ('FLAVOR_GOLD', 'FLAVOR_PRODUCTION')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_RANCH', 'FLAVOR_EXPANSION', 20
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1) UNION ALL
SELECT 'BUILDING_RANCH', 'FLAVOR_MOBILE', 5
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+10% [ICON_PRODUCTION] Production of Worker and Settler Units.[NEWLINE]
[NEWLINE]Gain 10 [ICON_PRODUCTION] Production whenever a [ICON_CITIZEN] Citizen is born in the City, scaling with Era.[NEWLINE]
[NEWLINE]Internal [ICON_INTERNATIONAL_TRADE] Trade Routes from this City generate +1 [ICON_FOOD] Food and [ICON_PRODUCTION] Production.[NEWLINE]
[NEWLINE]Nearby [ICON_RES_HORSE] Horses: +1 [ICON_FOOD] Food, +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_SHEEP] Sheep: +1 [ICON_FOOD] Food, +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_COW] Cow: +1 [ICON_FOOD] Food, +1 [ICON_GOLD] Gold.'
WHERE Tag = 'TXT_KEY_BUILDING_RANCH_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT OR REPLACE INTO Language_en_US (Text, Tag)
SELECT 'The {TXT_KEY_BUILDING_RANCH} is a Renaissance-era building that can help you grow and expand your Empire through training Worker and Settler units. '||
'It also gives Internal [ICON_INTERNATIONAL_TRADE] Trade Routes an additonal [ICON_FOOD] Food and [ICON_PRODUCTION] Production yield. '||
'The City must already posess a {TXT_KEY_BUILDING_STABLE} before a {TXT_KEY_BUILDING_RANCH} can be constructed.',
'TXT_KEY_BUILDING_RANCH_STRATEGY'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Update Homestead (America's UB) from More Unique Components for VP
-- Now replaces Ranch instead of Stable, but way earlier to unlock and does not require a Stable.
UPDATE Buildings SET
BuildingClass = 'BUILDINGCLASS_RANCH', PrereqTech = 'TECH_GUILDS',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_WINDMILL'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_WINDMILL')
WHERE Type = 'BUILDING_AMERICA_RANCH'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Civilization_BuildingClassOverrides SET
BuildingClassType = 'BUILDINGCLASS_RANCH'
WHERE BuildingType = 'BUILDING_AMERICA_RANCH'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Unit_BuildingClassRequireds SET
BuildingClassType = 'BUILDINGCLASS_RANCH'
WHERE UnitType = 'UNIT_AMERICA_PIONEER'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_YieldFromInternalTR SET
Yield = 1
WHERE BuildingType = 'BUILDING_AMERICA_RANCH'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldFromInternalTR (BuildingType, YieldType, Yield)
SELECT 'BUILDING_AMERICA_RANCH', 'YIELD_FOOD', 1
WHERE EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_ResourceYieldChanges
WHERE BuildingType = 'BUILDING_AMERICA_RANCH' AND YieldType = 'YIELD_PRODUCTION' AND ResourceType != 'RESOURCE_BISON'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_UnitCombatProductionModifiers
WHERE BuildingType = 'BUILDING_AMERICA_RANCH' AND UnitCombatType = 'UNITCOMBAT_MOUNTED'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'The Homestead boosts Bison in addition to all the resources normally boosted by a Stable, and all boosted resources gain additional food.', 'The {TXT_KEY_BUILDING_AMERICA_RANCH} gives additional yields to all the resources normally boosted by a {TXT_KEY_BUILDING_RANCH} with the addition of [ICON_RES_BISON] Bison. Increases Military Units supplied by this City''s population by 10%. ')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_STRATEGY'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, '. In addition to the regular abilities', ' which unlocked at a full era earlier than {TXT_KEY_BUILDING_RANCH} and does not require a {TXT_KEY_BUILDING_STABLE} to be constructed. In addition to the regular abilities')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_STRATEGY'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'The Homestead boosts the production of workers and settler units', 'The {TXT_KEY_BUILDING_AMERICA_RANCH} also gives additional boosts to the production of Workers and Settler Units')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_STRATEGY'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'Homestead', '{TXT_KEY_BUILDING_AMERICA_RANCH}')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_STRATEGY'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'Stable', '{TXT_KEY_BUILDING_RANCH}')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_STRATEGY'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, '+33% [ICON_PRODUCTION] Production when building Mounted Units and ', '')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_HELP'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'Internal [ICON_PRODUCTION] Production [ICON_INTERNATIONAL_TRADE] Trade Routes from this City generate +2 [ICON_PRODUCTION] Production', 'Internal [ICON_INTERNATIONAL_TRADE] Trade Routes from this City generate +1 [ICON_FOOD] Food and [ICON_PRODUCTION] Production.')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_HELP'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, '+2 [ICON_PRODUCTION] Production, ', '')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_HELP'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'Bison: +2 [ICON_FOOD] Food', 'Bison: +2 [ICON_FOOD] Food, +2 [ICON_PRODUCTION] Production')
WHERE Tag = 'TXT_KEY_BUILDING_AMERICA_RANCH_HELP'
AND EXISTS (SELECT * FROM Buildings WHERE Type='BUILDING_AMERICA_RANCH')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Chemist
UPDATE Buildings SET
LocalPopRequired = 12, IlliteracyFlatReduction = 1, Strategy = 'TXT_KEY_BUILDING_CHEMIST_STRATEGY',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FACTORY'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_FACTORY'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FACTORY')
WHERE Type = 'BUILDING_CHEMIST'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldFromBirth (BuildingType, YieldType, Yield)
SELECT 'BUILDING_CHEMIST', 'YIELD_SCIENCE', 25
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_YieldModifiers
WHERE BuildingType = 'BUILDING_CHEMIST' AND YieldType = 'YIELD_SCIENCE'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_YieldChanges
WHERE BuildingType = 'BUILDING_CHEMIST'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_CHEMIST', 'YIELD_SCIENCE', 17
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Gain 25 [ICON_RESEARCH] Science whenever a [ICON_CITIZEN] Citizen is born in the City, scaling with Era. +1 [ICON_RESEARCH] Science for every 6 [ICON_CITIZEN] Citizens in the City.[NEWLINE]
[NEWLINE]-1 [ICON_HAPPINESS_3] Unhappiness from [ICON_RESEARCH] Illiteracy.[NEWLINE]
[NEWLINE]Can only be constructed in a City that has more than 12 [ICON_CITIZEN] Citizens.'
WHERE Tag = 'TXT_KEY_BUILDING_CHEMIST_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT OR REPLACE INTO Language_en_US (Text, Tag)
SELECT 'The {TXT_KEY_BUILDING_CHEMIST} is an Industrial-era building which generates [ICON_RESEARCH] Science based on the size and growth of a City, and also reduces [ICON_HAPPINESS_3] Illiteracy. '||
'The City must have at least 12 [ICON_CITIZEN] Citizens and already posess a {TXT_KEY_BUILDING_PUBLIC_SCHOOL} before a {TXT_KEY_BUILDING_CHEMIST} can be constructed.',
'TXT_KEY_BUILDING_CHEMIST_STRATEGY'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_BuildingClassLocalYieldChanges
SELECT DISTINCT BuildingType, 'BUILDINGCLASS_CHEMIST', YieldType, YieldChange FROM Building_BuildingClassLocalYieldChanges
WHERE BuildingType = 'BUILDING_LABORATORY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'Hospitals', 'Chemists, Hospitals')
WHERE Tag = 'TXT_KEY_BUILDING_LABORATORY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- General Store
-- Swap VP Grocer and General Store icon
-- (VP Grocer icon is kinda too modern for the era it unlocked.)
-- Moved to Atomic Era, take 15% food kept from Medical Lab
-- Grocery line: Aqueduct -> Grocer -> General Store (or Agribusiness, Shopping Mall)
UPDATE Buildings SET
FoodKept = 15, PovertyFlatReduction = 1, PrereqTech = 'TECH_REFRIGERATION', Strategy = 'TXT_KEY_BUILDING_TCS_GROCER_STRATEGY',
IconAtlas = (SELECT IconAtlas FROM Buildings WHERE Type = 'BUILDING_GROCER'),
PortraitIndex = (SELECT PortraitIndex FROM Buildings WHERE Type = 'BUILDING_GROCER'),
UnlockedByBelief = (SELECT UnlockedByBelief FROM Buildings WHERE Type = 'BUILDING_MEDICAL_LAB'),
FaithCost = (SELECT FaithCost FROM Buildings WHERE Type = 'BUILDING_MEDICAL_LAB'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_MEDICAL_LAB'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_MEDICAL_LAB'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_MEDICAL_LAB')
WHERE Type = 'BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Buildings SET
PortraitIndex = 17
WHERE Type = 'BUILDING_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_GROCER'
WHERE BuildingType = 'BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_YieldModifiers
WHERE BuildingType = 'BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_YieldChanges
WHERE BuildingType = 'BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_TCS_GROCER', 'YIELD_FOOD', 13 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1) UNION ALL
SELECT 'BUILDING_TCS_GROCER', 'YIELD_GOLD', 25 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldFromYieldPercent (BuildingType, YieldIn, YieldOut, Value)
SELECT 'BUILDING_TCS_GROCER', 'YIELD_GOLD', 'YIELD_FOOD', 10
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_ResourceYieldChanges
WHERE BuildingType = 'BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_Flavors
WHERE BuildingType = 'BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_TCS_GROCER', 'FLAVOR_GROWTH', 40 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1) UNION ALL
SELECT 'BUILDING_TCS_GROCER', 'FLAVOR_GOLD', 35 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'General Store'
WHERE Tag = 'TXT_KEY_BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_FOOD] Food for every 10 [ICON_GOLD] Gold generated by the City. +1 [ICON_FOOD] Food and +2 [ICON_GOLD] Gold for every 8 [ICON_CITIZEN] Citizens in the City. 15% of [ICON_FOOD] Food is carried over after a new [ICON_CITIZEN] Citizen is born (effects stacks with Granary, Aqueduct, and Grocer).[NEWLINE]
[NEWLINE]-1 [ICON_HAPPINESS_3] Unhappiness from [ICON_GOLD] Poverty.'
WHERE Tag = 'TXT_KEY_BUILDING_TCS_GROCER_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT OR REPLACE INTO Language_en_US (Text, Tag)
SELECT 'The {TXT_KEY_BUILDING_TCS_GROCER} is a late-game building which decreases the amount of [ICON_FOOD] Food a City needs to increase in size by 15%. '||
'It generates [ICON_FOOD] Food and [ICON_GOLD] Gold based on the size of a City, and also generates [ICON_FOOD] Food from a some amount of the City''s [ICON_GOLD] Gold output. Helps reduces [ICON_HAPPINESS_3] Poverty. '||
'The City must already posess a {TXT_KEY_BUILDING_GROCER} before a {TXT_KEY_BUILDING_TCS_GROCER} can be constructed.',
'TXT_KEY_BUILDING_TCS_GROCER_STRATEGY'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Include General Store to Food of Thought reformation belief from Bare Necessities
UPDATE Buildings SET
UnlockedByBelief = (SELECT UnlockedByBelief FROM Buildings WHERE Type = 'BUILDING_MEDICAL_LAB'),
FaithCost = (SELECT FaithCost FROM Buildings WHERE Type = 'BUILDING_MEDICAL_LAB')
WHERE Type = 'BUILDING_TCS_GROCER'
AND EXISTS (SELECT * FROM Beliefs WHERE Type='BELIEF_FOT')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Belief_BuildingClassYieldChanges (BeliefType, BuildingClassType, YieldType, YieldChange)
SELECT DISTINCT bcyc.BeliefType, 'BUILDINGCLASS_TCS_GROCER', bcyc.YieldType, bcyc.YieldChange
FROM Belief_BuildingClassYieldChanges bcyc
WHERE bcyc.BeliefType = 'BELIEF_FOT'
AND EXISTS (SELECT * FROM Beliefs WHERE Type='BELIEF_FOT')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Belief_BuildingClassFaithPurchase (BeliefType, BuildingClassType)
SELECT 'BELIEF_FOT', 'BUILDINGCLASS_TCS_GROCER'
WHERE EXISTS (SELECT * FROM Beliefs WHERE Type='BELIEF_FOT')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'Grocers', 'Grocers, General Stores')
WHERE Tag = 'TXT_KEY_BELIEF_FOT'
AND EXISTS (SELECT * FROM Beliefs WHERE Type='BELIEF_FOT')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- New Medical Lab: 50% food from food output when a citizen is born (stack with Dispensary)
-- Medical Lab and Hospital reduce unhappiness from urbanization instead of poverty
UPDATE Buildings SET
FoodKept = 0, PovertyFlatReduction = 0, NoUnhappfromXSpecialists = 1
WHERE Type IN ('BUILDING_MEDICAL_LAB', 'BUILDING_HOSPITAL')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_GrowthExtraYield (BuildingType, YieldType, Yield)
SELECT 'BUILDING_MEDICAL_LAB', 'YIELD_FOOD', 50
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, '-1 [ICON_HAPPINESS_3] Unhappiness from [ICON_GOLD] Poverty.', '1 Specialist in this City no longer produces [ICON_HAPPINESS_3] Unhappiness from [ICON_URBANIZATION] Urbanization.')
WHERE Tag = 'TXT_KEY_BUILDING_HOSPITAL_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, '-1 [ICON_HAPPINESS_3] Unhappiness from [ICON_GOLD] Poverty.', '1 Specialist in this City no longer produces [ICON_HAPPINESS_3] Unhappiness from [ICON_URBANIZATION] Urbanization.')
WHERE Tag = 'TXT_KEY_BUILDING_MEDICAL_LAB_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, '15% of [ICON_FOOD] Food is carried over after a new [ICON_CITIZEN] Citizen is born.', 'Gain 50% of the [ICON_FOOD] Food output of the City as an instant boost to the City''s [ICON_FOOD] Food total when a [ICON_CITIZEN] Citizen is born in this City.')
WHERE Tag = 'TXT_KEY_BUILDING_MEDICAL_LAB_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'decreases the amount of [ICON_FOOD] Food a City needs to increase in size by 15% and ', '')
WHERE Tag = 'TXT_KEY_BUILDING_MEDICAL_LAB_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US SET
Text = REPLACE(Text, 'specialists.', 'specialists. Whenever a [ICON_CITIZEN] Citizen is born in the City, {TXT_KEY_BUILDING_MEDICAL_LAB} gives an instant boost to the City''s [ICON_FOOD] Food total from half amount of the City''s current [ICON_FOOD] Food output.')
WHERE Tag = 'TXT_KEY_BUILDING_MEDICAL_LAB_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Industrial Mine, now without limit but requires minimum amount of populations and a Mountain nearby
UPDATE BuildingClasses
SET MaxPlayerInstances = 0
WHERE Type = 'BUILDINGCLASS_INDUSTRIAL_MINE'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Buildings SET
LocalPopRequired = 15, Strategy = 'TXT_KEY_BUILDING_INDUSTRIAL_MINE_STRATEGY',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FACTORY'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_FACTORY'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FACTORY')
WHERE Type = 'BUILDING_INDUSTRIAL_MINE'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

DELETE FROM Building_YieldChanges
WHERE BuildingType = 'BUILDING_INDUSTRIAL_MINE'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_ResourceQuantity
SET Quantity = 1
WHERE BuildingType = 'BUILDING_INDUSTRIAL_MINE' AND ResourceType = 'RESOURCE_COAL'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_ResourceQuantity (BuildingType, ResourceType, Quantity)
SELECT 'BUILDING_INDUSTRIAL_MINE', 'RESOURCE_IRON', 1
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT INTO Building_YieldPerXTerrainTimes100 (BuildingType, TerrainType, YieldType, Yield)
SELECT 'BUILDING_INDUSTRIAL_MINE', 'TERRAIN_MOUNTAIN', 'YIELD_PRODUCTION', 100
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'City gains +1 [ICON_PRODUCTION] Production for every Mountain within the workable tiles.[NEWLINE]
[NEWLINE]Provides +1 [ICON_RES_COAL] Coal and [ICON_RES_IRON] Iron.[NEWLINE]
[NEWLINE]Can only be constructed in a City that has more than 15 [ICON_CITIZEN] Citizens and nearby to a Mountain.'
WHERE Tag = 'TXT_KEY_BUILDING_INDUSTRIAL_MINE_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT OR REPLACE INTO Language_en_US (Text, Tag)
SELECT 'The {TXT_KEY_BUILDING_INDUSTRIAL_MINE} is an Industrial-era building that provides [ICON_PRODUCTION] Production for every Mountain within the workable City tiles. '||
'Each {TXT_KEY_BUILDING_INDUSTRIAL_MINE} provides +1 [ICON_RES_IRON] Iron and [ICON_RES_COAL] Coal. '||
'The City must be nearby to a Mountain, and have at least 15 [ICON_CITIZEN] Citizens before an {TXT_KEY_BUILDING_INDUSTRIAL_MINE} can be constructed.',
'TXT_KEY_BUILDING_INDUSTRIAL_MINE_STRATEGY'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Buildings SET
Defense = 500, ExtraCityHitPoints = 100, CitySupplyFlat = 1, CitySupplyModifier = 10, AllowsRangeStrike = 1, Strategy = 'TXT_KEY_BUILDING_COASTAL_BATTERY_STRATEGY',
PrereqTech = (SELECT PrereqTech FROM Buildings WHERE Type = 'BUILDING_FORTRESS'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_FORTRESS'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_FORTRESS'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_FORTRESS')
WHERE Type = 'BUILDING_COASTAL_BATTERY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Building_ClassesNeededInCity
SET BuildingClassType = 'BUILDINGCLASS_HARBOR'
WHERE BuildingType = 'BUILDING_COASTAL_BATTERY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Increases [ICON_SILVER_FIST] Military Unit Supply Cap by 1, and Military Units Supplied by this City''s population increased by 10%. Increases City Hit Points by 100.[NEWLINE][NEWLINE]Can only be constructed in a Coastal City.'
WHERE Tag = 'TXT_KEY_BUILDING_COASTAL_BATTERY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

INSERT OR REPLACE INTO Language_en_US (Text, Tag)
SELECT 'The {TXT_KEY_BUILDING_COASTAL_BATTERY} is a Renaissance-era military building that increases Defense Strength and Hit Points, making the City more difficult to capture. '||
'Increases Military Unit Supply Cap by 1 and Military Units supplied by this City''s population by 10%. '||
'The City must be on Coast, and already posess a {TXT_KEY_BUILDING_HARBOR} before a {TXT_KEY_BUILDING_COASTAL_BATTERY} can be constructed.',
'TXT_KEY_BUILDING_COASTAL_BATTERY_STRATEGY'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Harbor (-100 HP, -1 Supply Cap)
UPDATE  Buildings SET
ExtraCityHitPoints = ExtraCityHitPoints - 100,
CitySupplyFlat = CitySupplyFlat - 1
WHERE BuildingClass = 'BUILDINGCLASS_HARBOR'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Supply Cap by 2, and City Hit Points by 150', 'Supply Cap by 1, and City Hit Points by 50')
WHERE Tag = 'TXT_KEY_BUILDING_HARBOR_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);

-- Add Coastal Battery to Military-Industrial Complex (Autocracy) tenet
INSERT  INTO Policy_BuildingClassYieldChanges
(PolicyType, BuildingClassType, YieldType, YieldChange)
SELECT DISTINCT bcyc.PolicyType, 'BUILDINGCLASS_COASTAL_BATTERY', bcyc.YieldType, bcyc.YieldChange
FROM Policy_BuildingClassYieldChanges bcyc
WHERE bcyc.PolicyType = 'POLICY_MOBILIZATION'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'CBPMC_INDUSTRIAL' AND Value= 1);

-- Add Coastal Battery to Defender of Faith belief
-- +1 Faith and +2 Culture for all of these buildings.
INSERT  INTO Belief_BuildingClassYieldChanges
(BeliefType, BuildingClassType, YieldType, YieldChange)
SELECT DISTINCT bcyc.BeliefType, 'BUILDINGCLASS_COASTAL_BATTERY', bcyc.YieldType, bcyc.YieldChange
FROM Belief_BuildingClassYieldChanges bcyc
WHERE bcyc.BeliefType = 'BELIEF_DEFENDER_FAITH'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'CBPMC_INDUSTRIAL' AND Value= 1);

-- Add Coastal Battery to Oda Nobunaga's Ubique Ability (Japan)
-- +1 Faith and Culture for all of these buildings.
INSERT  INTO Trait_BuildingClassYieldChanges
(TraitType, BuildingClassType, YieldType, YieldChange)
SELECT DISTINCT bcyc.TraitType, 'BUILDINGCLASS_COASTAL_BATTERY', bcyc.YieldType, bcyc.YieldChange
FROM Trait_BuildingClassYieldChanges bcyc
WHERE bcyc.TraitType = 'TRAIT_FIGHT_WELL_DAMAGED'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type = 'CBPMC_INDUSTRIAL' AND Value= 1);

-- Remove "--Wikipedia" from pedia texts
UPDATE Language_en_US SET
Text = REPLACE(Text, '[NEWLINE][NEWLINE]--Wikipedia', '')
WHERE Tag IN (  'TXT_KEY_BUILDING_TEXTILE_MILL_PEDIA',
                'TXT_KEY_BUILDING_RANCH_PEDIA',
                'TXT_KEY_BUILDING_CHEMIST_PEDIA',
                'TXT_KEY_BUILDING_TCS_GROCER_PEDIA',
                'TXT_KEY_BUILDING_INDUSTRIAL_MINE_PEDIA',
                'TXT_KEY_BUILDING_COASTAL_BATTERY_PEDIA')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_INDUSTRIAL' AND Value= 1);
