DELETE FROM Building_YieldModifiers
WHERE BuildingType IN ('BUILDING_APOTHECARY', 'BUILDING_BLACKSMITH', 'BUILDING_PRINTER')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

-- Blacksmith
DELETE FROM Building_ResourceQuantityRequirements
WHERE BuildingType = 'BUILDING_BLACKSMITH'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1 );

DELETE FROM Building_UnitCombatProductionModifiers
WHERE BuildingType = 'BUILDING_BLACKSMITH'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1 );

UPDATE Buildings SET
GoldMaintenance = 1, MaxStartEra = 'ERA_INDUSTRIAL',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_TEMPLE'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_TEMPLE')
WHERE Type = 'BUILDING_BLACKSMITH'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_BLACKSMITH', 'FLAVOR_MILITARY_TRAINING', 15
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_UnitCombatProductionModifiers
SELECT 'BUILDING_BLACKSMITH', Type, 15 FROM UnitCombatInfos
WHERE Type IN ('UNITCOMBAT_MELEE', 'UNITCOMBAT_MOUNTED')
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldFromUnitProduction
SELECT 'BUILDING_BLACKSMITH', 'YIELD_GOLD', 5 FROM Buildings
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_BLACKSMITH', 'YIELD_PRODUCTION', 15
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
SELECT 'BUILDING_BLACKSMITH', 'BUILDINGCLASS_FORGE'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_PRODUCTION] Production. +1 [ICON_PRODUCTION] Production for every 6 [ICON_CITIZEN] Population.[NEWLINE]
[NEWLINE]+15% [ICON_PRODUCTION] Production towards Pre-Gunpowder Melee Units and Mounted Units.[NEWLINE]
[NEWLINE]When you construct a Unit in this City, gain [ICON_GOLD] Gold equal to 5% of the Unit''s [ICON_PRODUCTION] Production cost.'
WHERE Tag = 'TXT_KEY_BUILDING_BLACKSMITH_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

-- Dispensary (rename from Apothecary, to prevent name conflict with other mod)
UPDATE Buildings SET
PrereqTech = 'TECH_CHEMISTRY', FreeStartEra = 'ERA_POSTMODERN',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_GROCER'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GROCER'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GROCER')
WHERE Type = 'BUILDING_APOTHECARY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType)
SELECT 'BUILDING_APOTHECARY', 'BUILDINGCLASS_HERBALIST'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_GrowthExtraYield (BuildingType, YieldType, Yield)
SELECT 'BUILDING_APOTHECARY', 'YIELD_FOOD', 20
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldFromYieldPercent (BuildingType, YieldIn, YieldOut, Value)
SELECT 'BUILDING_APOTHECARY', 'YIELD_FOOD', 'YIELD_SCIENCE', 10
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = 'Dispensary'
WHERE Tag = 'TXT_KEY_BUILDING_APOTHECARY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_FOOD] Food and [ICON_RESEARCH] Science. 10% of the City''s [ICON_FOOD] Food converted into [ICON_RESEARCH] Science every turn. '||
'+20% of the [ICON_FOOD] Food of the City is added to the current [ICON_FOOD] Food total when a [ICON_CITIZEN] Citizen is born in this City.'
WHERE Tag = 'TXT_KEY_BUILDING_APOTHECARY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = 'The word "dispensary" is in common use today to describe a place or room where drugs are stored, made up according to prescriptions, and dispensed.'||
'While it always had this meaning, it was also used to describe "a charitable institution where medicines are dispensed and medical advice given gratis or for a small charge."'||
'These institutions provided care on an outpatient basis, including home visiting, and, in their general economy, they resembled in many ways the health centers of today.'
WHERE Tag = 'TXT_KEY_BUILDING_APOTHECARY_PEDIA'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

-- Alchemist
UPDATE Buildings SET
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_UNIVERSITY'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_UNIVERSITY'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_UNIVERSITY')
WHERE Type = 'BUILDING_ALCHEMIST'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldFromYieldPercent (BuildingType, YieldIn, YieldOut, Value)
SELECT 'BUILDING_ALCHEMIST', 'YIELD_SCIENCE', 'YIELD_FAITH', 15
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Building_ResourceYieldChanges
SET Yield = 1
WHERE BuildingType = 'BUILDING_ALCHEMIST' AND ResourceType = 'RESOURCE_GOLD'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_ResourceYieldChanges (BuildingType, ResourceType, YieldType, Yield)
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_AMBER',  'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_JADE',   'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_LAPIS',  'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_LocalResourceOrs (BuildingType, ResourceType)
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_JADE' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_AMBER' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_ALCHEMIST', 'RESOURCE_LAPIS' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

DELETE FROM Building_Flavors
WHERE BuildingType = 'BUILDING_ALCHEMIST' AND FlavorType = 'FLAVOR_GROWTH'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '15% of the City''s [ICON_RESEARCH] Science converted into [ICON_PEACE] Faith every turn.[NEWLINE]
[NEWLINE]Nearby [ICON_RES_GEMS] Gems: +1 [ICON_RESEARCH] Science.[NEWLINE]Nearby [ICON_RES_GOLD] Gold: +1 [ICON_RESEARCH] Science.[NEWLINE]Nearby [ICON_RES_SILVER] Silver: +1 [ICON_RESEARCH] Science.[NEWLINE]Nearby [ICON_RES_AMBER] Amber: +1 [ICON_RESEARCH] Science.[NEWLINE]Nearby [ICON_RES_JADE] Jade: +1 [ICON_RESEARCH] Science.[NEWLINE]Nearby [ICON_RES_LAPIS] Lapis Lazuli: +1 [ICON_RESEARCH] Science.'
WHERE Tag = 'TXT_KEY_BUILDING_ALCHEMIST_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

-- Sewer System
UPDATE Buildings SET
Happiness = 0, FoodKept = 0, ExtraCityHitPoints = 0, NoUnhappfromXSpecialists = 1, FreeStartEra = 'ERA_POSTMODERN',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_OPERA_HOUSE'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_OPERA_HOUSE') + 1,
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_OPERA_HOUSE')
WHERE Type = 'BUILDING_SEWER_SYSTEM'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_GrowthExtraYield (BuildingType, YieldType, Yield)
SELECT 'BUILDING_SEWER_SYSTEM', 'YIELD_FOOD', 30
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_SEWER_SYSTEM', 'YIELD_GOLDEN_AGE_POINTS', 10
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Building_Flavors
SET Flavor = 5
WHERE BuildingType = 'BUILDING_SEWER_SYSTEM' AND FlavorType = 'FLAVOR_HAPPINESS'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

DELETE FROM Building_Flavors
WHERE BuildingType = 'BUILDING_SEWER_SYSTEM' AND FlavorType = 'FLAVOR_CITY_DEFENSE'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+1 [ICON_GOLDEN_AGE] Golden Age Point for every 10 [ICON_CITIZEN] Population. '||
'+30% of the [ICON_FOOD] Food of the City is added to the current [ICON_FOOD] Food total when a [ICON_CITIZEN] Citizen is born in this City.[NEWLINE]
[NEWLINE]1 Specialist in this City no longer produces [ICON_HAPPINESS_3] Unhappiness from Urbanization.'
WHERE Tag = 'TXT_KEY_BUILDING_SEWER_SYSTEM_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

-- Printer
UPDATE Buildings SET
SpecialistCount = 0, GreatPeopleRateModifier = 5, FreeStartEra = 'ERA_POSTMODERN',
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_GROCER'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GROCER'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GROCER')
WHERE Type = 'BUILDING_PRINTER'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

DELETE FROM Building_ClassesNeededInCity
WHERE BuildingType = 'BUILDING_PRINTER' AND BuildingClassType = 'BUILDINGCLASS_UNIVERSITY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PRINTER', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_TOURISM', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_PRINTER', 'YIELD_SCIENCE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_TOURISM', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1) UNION ALL
SELECT 'BUILDING_PRINTER', 'YIELD_CULTURE', 10 WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);

UPDATE Language_en_US
SET Text = '+5% [ICON_GREAT_PEOPLE] Great People generation in this City. +1 [ICON_CULTURE] Culture, [ICON_TOURISM] Tourism, and [ICON_RESEARCH] Science. +1 [ICON_CULTURE] Culture, [ICON_TOURISM] Tourism, and [ICON_RESEARCH] Science for every 10 [ICON_CITIZEN] Population.'
WHERE Tag = 'TXT_KEY_BUILDING_PRINTER_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_MEDIRENA' AND Value= 1);
