UPDATE Buildings SET
ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_GRANARY'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_GRANARY'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_GRANARY')
WHERE Type = 'BUILDING_CORRAL'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings SET
EnhancedYieldTech = 'TECH_ARCHAEOLOGY'
WHERE Type = 'BUILDING_CORRAL' AND EnhancedYieldTech IS NOT NULL
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Maximum', '[NEWLINE][NEWLINE]Maximum')
WHERE Tag = 'TXT_KEY_BUILDING_CORRAL_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Industrialization', '[COLOR_CYAN]{TXT_KEY_TECH_ARCHAEOLOGY_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_CORRAL_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Industrialization', '[COLOR_CYAN]{TXT_KEY_TECH_ARCHAEOLOGY_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_CORRAL_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_CORRAL_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_CORRAL_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings SET
ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_AQUEDUCT'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_AQUEDUCT'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_AQUEDUCT')
WHERE Type = 'BUILDING_FOUNDRY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Maximum', '[NEWLINE][NEWLINE]Maximum')
WHERE Tag = 'TXT_KEY_BUILDING_FOUNDRY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Industrialization', '[COLOR_CYAN]{TXT_KEY_TECH_INDUSTRIALIZATION_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_FOUNDRY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Industrialization', '[COLOR_CYAN]{TXT_KEY_TECH_INDUSTRIALIZATION_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_FOUNDRY_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_FOUNDRY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_FOUNDRY_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings SET
ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_TRAINSTATION'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_TRAINSTATION'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_TRAINSTATION')
WHERE Type = 'BUILDING_DEEP_MINE'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Maximum', '[NEWLINE][NEWLINE]Maximum')
WHERE Tag = 'TXT_KEY_BUILDING_DEEP_MINE_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Robotics', '[COLOR_CYAN]{TXT_KEY_TECH_ROBOTICS_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_DEEP_MINE_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Robotics', '[COLOR_CYAN]{TXT_KEY_TECH_ROBOTICS_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_DEEP_MINE_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_DEEP_MINE_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_DEEP_MINE_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings SET
PrereqTech = 'TECH_COMBUSTION',
ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_HOSPITAL'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_HOSPITAL'),
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_HOSPITAL')
WHERE Type = 'BUILDING_BIOFUEL_REFINERY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Maximum', '[NEWLINE][NEWLINE]Maximum')
WHERE Tag = 'TXT_KEY_BUILDING_BIOFUEL_REFINERY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Ecology', '[COLOR_CYAN]{TXT_KEY_TECH_ECOLOGY_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_BIOFUEL_REFINERY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Ecology', '[COLOR_CYAN]{TXT_KEY_TECH_ECOLOGY_TITLE}[ENDCOLOR]')
WHERE Tag = 'TXT_KEY_BUILDING_BIOFUEL_REFINERY_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_BIOFUEL_REFINERY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_BIOFUEL_REFINERY_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE Buildings SET
ConquestProb = (SELECT ConquestProb FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
NeverCapture = (SELECT NeverCapture FROM Buildings WHERE Type = 'BUILDING_RECYCLING_CENTER'),
Cost = (SELECT Cost FROM Buildings WHERE Type = 'BUILDING_SPACESHIP_FACTORY'),
GoldMaintenance = (SELECT GoldMaintenance FROM Buildings WHERE Type = 'BUILDING_SPACESHIP_FACTORY') + 2,
HurryCostModifier = (SELECT HurryCostModifier FROM Buildings WHERE Type = 'BUILDING_SPACESHIP_FACTORY')
WHERE Type = 'BUILDING_ENRICHMENT_FACILITY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'Maximum', '[NEWLINE][NEWLINE]Maximum')
WHERE Tag = 'TXT_KEY_BUILDING_ENRICHMENT_FACILITY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_ENRICHMENT_FACILITY_HELP'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);

UPDATE  Language_en_US SET
Text = REPLACE(Text, 'empire', 'Empire')
WHERE Tag = 'TXT_KEY_BUILDING_ENRICHMENT_FACILITY_STRATEGY'
AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='CBPMC_RESBUILDING' AND Value= 1);
